#spring:
#  r2dbc:
#    url: r2dbc:mariadb://deogicorgi.home:23306/ebs?useUnicode=true&characterEncoding=utf8
#    username: deogicorgi
#    password: 8813
#
#  jpa.properties.hibernate.dialect: org.hibernate.dialect.MariaDB103Dialect
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 18080

database:
  #    url: r2dbc:mariadb://deogicorgi.home:23306/ebs?useUnicode=true&characterEncoding=utf8
  host: deogicorgi.home
  port: 23306
  db: ebs
  username: deogicorgi
  password: 8813
  max-size: 100

logging.level.org.springframework.r2dbc: DEBUG

